### ISSUE TITLE
Need to copy new files in build folder to docs folder when using with GH actions

### ISSUE THREAD

**Issue by protimroy** [sea-grass/goku#4]
After building changes with 

```
../goku/zig-out/bin/goku site -o build
```

There are new files which need to be copied to the docs folder for the site to show the new information even though the build succeeded on GH.

![image](https://github.com/user-attachments/assets/01b1e6e1-3e20-49f8-b4a3-07aa7983fabe)

So, the command should be

```
../goku/zig-out/bin/goku site -o build && cp -r build/* docs/
```

I can submit a PR for a bash script to be executed when the programmer is ready to build and deploy. 

Note: This is not necessary for localhost / hot reload; it is only necessary for deploying to GH pages through GH actions.

**Comment by sea-grass** [comment]
If you're using `docs/` as a subpath for your GH pages content, you can adjust your `goku` command to output the generated site directly to the `docs/` folder, rather than the `build/` folder and save the copy step:

```sh
../goku/zig-out/bin/goku site -o docs
```
